schedules:
- cron: 0 5 * * 1,2,3,4,5
  branches:
    include:
    - dev
  always: true
- cron: 0 7 * * 1,2,3,4,5
  branches:
    include:
    - dev
  always: true
- cron: 0 19 * * 1,2,3,4,5
  branches:
    include:
    - refs/heads/dev
  always: true
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/dev
jobs:
- job: Job_2
  displayName: Public UI tests
  timeoutInMinutes: 160
  cancelTimeoutInMinutes: 10
  condition: succeededOrFailed()
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
    fetchTags: false
  - task: UsePythonVersion@0
    displayName: Use Python 3.10
    retryCountOnTaskFailure: 5
    timeoutInMinutes: 5
    inputs:
      versionSpec: 3.10
  # - task: AzureKeyVault@2
  #   displayName: 'Azure Key Vault: s101d01-kv-ees-01'
  #   inputs:
  #     ConnectedServiceName: 372f9261-ade1-429b-be3c-aebd417646ca
  #     KeyVaultName: s101d01-kv-ees-01
  #     SecretsFilter: ees-test-ADMIN-PASSWORD,ees-test-ANALYST-PASSWORD
  
  - task: PythonScript@0
    displayName: Public UI tests
    inputs:
      scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
      arguments: --admin-pass "test" --analyst-pass "test" --expiredinvite-pass "test" --env "dev" --file "tests/general_public/" --processes 2
      workingDirectory: tests/robot-tests
  - task: PythonScript@0
    displayName: Public UI tests - rerun failed suites
    condition: not(succeeded())
    inputs:
      scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
      arguments: --admin-pass "test" --analyst-pass "test" --expiredinvite-pass "test" --env "dev" --file "tests/general_public/" --processes 2 --rerun-failed-suites
      workingDirectory: tests/robot-tests
  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: tests/robot-tests/test-results/xunit.xml
      failTaskOnFailedTests: true
  - task: PublishPipelineArtifact@1
    displayName: Publish Test Pipeline Artifact
    inputs:
      path: tests/robot-tests/test-results/
      artifactName: test-results-public
- job: Job_3
  displayName: Publish release and amend suites
  timeoutInMinutes: 160
  cancelTimeoutInMinutes: 10
  condition: succeededOrFailed()
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
    fetchTags: false
  - task: UsePythonVersion@0
    displayName: Use Python 3.10
    retryCountOnTaskFailure: 5
    timeoutInMinutes: 5
    inputs:
      versionSpec: 3.10
  # - task: AzureKeyVault@2
  #   displayName: 'Azure Key Vault: s101d01-kv-ees-01'
  #   inputs:
  #     ConnectedServiceName: 372f9261-ade1-429b-be3c-aebd417646ca
  #     KeyVaultName: s101d01-kv-ees-01
  #     SecretsFilter: ees-test-ADMIN-PASSWORD,ees-test-ANALYST-PASSWORD,ees-test-expiredinvite-password
  - task: PythonScript@0
    displayName: Publish release and amend UI tests
    condition: succeededOrFailed()
    inputs:
      scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
      arguments: --admin-pass "$(ees-test-ADMIN-PASSWORD)" --analyst-pass "$(ees-test-ANALYST-PASSWORD)" --expiredinvite-pass "$(ees-test-expiredinvite-password)" --env "dev" --file "tests/admin_and_public_2" --processes 2
      workingDirectory: tests/robot-tests
  - task: PythonScript@0
    displayName: 'Publish release and amend UI tests - rerun failed suites'
    condition: not(succeeded())
    inputs:
      scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
      arguments: --admin-pass "$(ees-test-ADMIN-PASSWORD)" --analyst-pass "$(ees-test-ANALYST-PASSWORD)" --expiredinvite-pass "$(ees-test-expiredinvite-password)" --env "dev" --file "tests/admin_and_public_2" --processes 2 --rerun-failed-suites
      workingDirectory: tests/robot-tests
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFiles: tests/robot-tests/test-results/xunit.xml
      failTaskOnFailedTests: true
  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact
    inputs:
      path: tests/robot-tests/test-results/
      artifactName: test-results-admin-and-public-2
- job: Phase_1
  displayName: Admin UI tests
  timeoutInMinutes: 160
  cancelTimeoutInMinutes: 10
  condition: succeededOrFailed()
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
    fetchTags: false
  - task: UsePythonVersion@0
    displayName: Use Python 3.10
    retryCountOnTaskFailure: 5
    timeoutInMinutes: 5
    inputs:
      versionSpec: 3.10
  # - task: AzureKeyVault@2
  #   displayName: 'Azure Key Vault: s101d01-kv-ees-01'
  #   inputs:
  #     ConnectedServiceName: 372f9261-ade1-429b-be3c-aebd417646ca
  #     KeyVaultName: s101d01-kv-ees-01
  #     SecretsFilter: ees-test-ADMIN-PASSWORD,ees-test-ANALYST-PASSWORD,ees-test-expiredinvite-password
  - task: PythonScript@0
    displayName: Admin UI tests
    condition: succeededOrFailed()
    inputs:
      scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
      arguments: --admin-pass  "$(ees-test-ADMIN-PASSWORD)" --analyst-pass  "$(ees-test-ANALYST-PASSWORD)" --expiredinvite-pass "$(ees-test-expiredinvite-password)" --env "dev" --file "tests/admin" --processes 2
      workingDirectory: tests/robot-tests
  - task: PythonScript@0
    displayName: Admin UI tests - rerun failed suites
    condition: not(succeeded())
    inputs:
      scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
      arguments: --admin-pass  "$(ees-test-ADMIN-PASSWORD)" --analyst-pass  "$(ees-test-ANALYST-PASSWORD)" --expiredinvite-pass "$(ees-test-expiredinvite-password)" --env "dev" --file "tests/admin" --processes 2 --rerun-failed-suites
      workingDirectory: tests/robot-tests
  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: tests/robot-tests/test-results/xunit.xml
      failTaskOnFailedTests: true
  - task: PublishPipelineArtifact@1
    displayName: Publish Test Pipeline Artifact
    condition: succeededOrFailed()
    inputs:
      path: tests/robot-tests/test-results/
      artifactName: test-results-admin
- job: Job_1
  displayName: Admin & public suites
  timeoutInMinutes: 160
  cancelTimeoutInMinutes: 10
  condition: succeededOrFailed()
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
    fetchTags: false
  - task: UsePythonVersion@0
    displayName: Use Python 3.10
    retryCountOnTaskFailure: 5
    timeoutInMinutes: 5
    inputs:
      versionSpec: 3.10
  # - task: AzureKeyVault@2
  #   displayName: 'Azure Key Vault: s101d01-kv-ees-01'
  #   inputs:
  #     ConnectedServiceName: 372f9261-ade1-429b-be3c-aebd417646ca
  #     KeyVaultName: s101d01-kv-ees-01
  #     SecretsFilter: ees-test-ADMIN-PASSWORD,ees-test-ANALYST-PASSWORD,ees-test-expiredinvite-password
  - task: PythonScript@0
    displayName: Admin public UI tests
    inputs:
      scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
      arguments: --admin-pass  "$(ees-test-ADMIN-PASSWORD)" --analyst-pass  "$(ees-test-ANALYST-PASSWORD)" --expiredinvite-pass "$(ees-test-expiredinvite-password)" --env "dev" --file "tests/admin_and_public" --processes 2
      workingDirectory: tests/robot-tests
  - task: PythonScript@0
    displayName: Admin public UI tests - rerun failed suites
    condition: not(succeeded())
    inputs:
      scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
      arguments: --admin-pass  "$(ees-test-ADMIN-PASSWORD)" --analyst-pass  "$(ees-test-ANALYST-PASSWORD)" --expiredinvite-pass "$(ees-test-expiredinvite-password)" --env "dev" --file "tests/admin_and_public" --processes 2 --rerun-failed-suites
      workingDirectory: tests/robot-tests
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFiles: tests/robot-tests/test-results/xunit.xml
  - task: PublishPipelineArtifact@1
    displayName: Publish Test Pipeline Artifact
    inputs:
      path: tests/robot-tests/test-results/
      artifactName: test-results-admin-public
...
