variables:
  BuildConfiguration: 'Release'
  CI: true

trigger: [ 'master' ]
pr: [ 'master' ]

jobs:
  - job: 'Backend'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: 'DotNetCoreCLI@2'
        displayName: 'Restore'
        inputs:
          command: 'restore'
          projects: '**/GovUk.*/*csproj'
          feedsToUse: config
          nugetConfigPath: src/nuget.config
      - task: 'DotNetCoreCLI@2'
        displayName: 'Build'
        inputs:
          projects: '**/GovUk.*/*csproj'
          arguments: '--configuration $(BuildConfiguration)'
      - task: 'DotNetCoreCLI@2'
        displayName: 'Test'
        inputs:
          command: 'test'
          projects: '**/GovUk.*[Tt]ests/*.csproj'
          arguments: '--configuration $(BuildConfiguration)'

      - task: 'DotNetCoreCLI@2'
        displayName: 'Publish'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/GovUk.*/*.csproj'
          arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
          zipAfterPublish: True
      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'backend'
          targetPath: '$(Build.ArtifactStagingDirectory)'

  - job: 'Frontend'
    pool:
      vmImage: 'ubuntu-16.04'
      demands: 'npm'
    steps:
      - task: 'Npm@1'
        displayName: 'npm ci'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'ci'
      - task: 'Npm@1'
        displayName: 'npm run lint'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'run lint'
      - task: 'Npm@1'
        displayName: 'npm run format:check'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'run format:check'
      - task: 'Npm@1'
        displayName: 'npm run test:ci'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'run test:ci'
      - task: 'PublishTestResults@2'
        displayName: 'Publish frontend test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/junit.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)/src/explore-education-statistics-frontend'
          testRunTitle: 'Frontend Jest tests'
      - task: 'Bash@3'
        displayName: 'Remove node_modules'
        inputs:
          targetType: 'inline'
          script: 'rm -rf $(System.DefaultWorkingDirectory)/src/explore-education-statistics-frontend/node_modules/'
      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'frontend'
          targetPath: 'src/explore-education-statistics-frontend'
  - job: 'MiscellaneousArtifacts'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: PublishPipelineArtifact@0
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'robot-tests'
          targetPath: 'tests/robot-tests'
      - task: PublishPipelineArtifact@0
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'newman-tests'
          targetPath: 'tests/newman'
      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish ARM templates'
        inputs:
          artifactName: 'arm-templates'
          targetPath: 'armTemplates'

#  - job: 'Frontend_Build'
#    dependsOn: 'Frontend_Test'
#    pool:
#      vmImage: 'ubuntu-16.04'
#      demands: 'npm'
#    steps:
#    - task: 'Npm@1'
#      displayName: 'npm ci'
#      inputs:
#        command: 'custom'
#        workingDir: 'src/explore-education-statistics-frontend'
#        verbose: false
#        customCommand: 'ci'
#    - task: 'Npm@1'
#      displayName: 'npm run build:test'
#      inputs:
#        command: 'custom'
#        workingDir: 'src/explore-education-statistics-frontend'
#        verbose: false
#        customCommand: 'run build:test'
#    - task: 'ArchiveFiles@2'
#      displayName: 'Archive frontend'
#      inputs:
#        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/src/explore-education-statistics-frontend'
#        includeRootFolder: false
#        archiveFile: '$(Build.ArtifactStagingDirectory)/explore-education-statistics-frontend.zip'
#    - task: 'PublishPipelineArtifact@0'
#      displayName: 'Publish Pipeline Artifact'
#      inputs:
#        artifactName: 'frontend'
#        targetPath: '$(Build.ArtifactStagingDirectory)'
