variables:
  BuildConfiguration: 'Release'
  CI: true

trigger: [ 'master' ]
pr: [ 'master' ]

jobs:
  - job: 'Backend'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: 'DotNetCoreCLI@2'
        displayName: 'Restore'
        inputs:
          command: 'restore'
          projects: '**/GovUk.*/*csproj'
      - task: 'DotNetCoreCLI@2'
        displayName: 'Build'
        inputs:
          projects: '**/GovUk.*/*csproj'
          arguments: '--configuration $(BuildConfiguration)'
      - task: 'DotNetCoreCLI@2'
        displayName: 'Test'
        inputs:
          command: 'test'
          projects: '**/GovUk.*[Tt]ests/*.csproj'
          arguments: '--configuration $(BuildConfiguration)'

      - task: 'DotNetCoreCLI@2'
        displayName: 'Publish'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/GovUk.*/*.csproj'
          arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
          zipAfterPublish: True
      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'backend'
          targetPath: '$(Build.ArtifactStagingDirectory)'

  - job: 'PublicFrontendBuildTest'
    displayName: 'Public frontend build for test'
    pool:
      vmImage: 'ubuntu-16.04'
      demands: 'npm'
    steps:
      - task: 'Npm@1'
        displayName: 'npm ci'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'ci'
      - task: 'Npm@1'
        displayName: 'npm run lint'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'run lint'
      - task: 'Npm@1'
        displayName: 'npm run format:check'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'run format:check'
      - task: 'Npm@1'
        displayName: 'npm run test:ci'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'run test:ci'
      - task: 'PublishTestResults@2'
        displayName: 'Publish frontend test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/junit.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)/src/explore-education-statistics-frontend'
          testRunTitle: 'Frontend Jest tests'
      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'frontend'
          targetPath: 'src/explore-education-statistics-frontend'
      - task: 'Npm@1'
        displayName: 'npm run build:test'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'run build:test'
      - task: 'ArchiveFiles@2'
        displayName: 'Archive frontend'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/src/explore-education-statistics-frontend'
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory}/public-frontend-test.zip'
      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'public-frontend-test'
          targetPath: '$(Build.ArtifactStagingDirectory)'

  - job: 'PublicFrontendBuildStage'
    displayName: 'Public frontend build for stage'
    dependsOn: 'PublicFrontendBuildTest'
    pool:
      vmImage: 'ubuntu-16.04'
      demands: 'npm'
    steps:
      - task: 'Npm@1'
        displayName: 'npm run test:ci'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'run test:ci'
      - task: 'Npm@1'
        displayName: 'npm run build:stage'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'run build:stage'
      - task: 'ArchiveFiles@2'
        displayName: 'Archive frontend'
        inputs:
          rootFolderOrFile: 'src/explore-education-statistics-frontend'
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/public-frontend-stage.zip'
      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'public-frontend-stage'
          targetPath: '$(Build.ArtifactStagingDirectory)'

  - job: 'PublicFrontendBuildLive'
    displayName: 'Public frontend build for live'
    dependsOn: 'PublicFrontendBuildTest'
    pool:
      vmImage: 'ubuntu-16.04'
      demands: 'npm'
    steps:
      - task: 'Npm@1'
        displayName: 'npm run test:ci'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'run test:ci'
      - task: 'Npm@1'
        displayName: 'npm run build:live'
        inputs:
          command: 'custom'
          workingDir: 'src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'run build:live'
      - task: 'ArchiveFiles@2'
        displayName: 'Archive frontend'
        inputs:
          rootFolderOrFile: 'src/explore-education-statistics-frontend'
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/explore-education-statistics-frontend-live.zip'
      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'public-frontend-live'
          targetPath: '$(Build.ArtifactStagingDirectory)'

  - job: 'MiscellaneousArtifacts'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: PublishPipelineArtifact@0
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'robot-tests'
          targetPath: 'tests/robot-tests'
      - task: PublishPipelineArtifact@0
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'newman-tests'
          targetPath: 'tests/newman'
      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish ARM templates'
        inputs:
          artifactName: 'arm-templates'
          targetPath: 'armTemplates'
